### ISSUE TITLE
[FEAT] 마이페이지 UI 구현

### ISSUE THREAD

**Issue by zzikbu** [CatDesignProject/CUKZ-FE#14]
# 👀 이슈 (issue)

마이페이지 UI 구현

# 🚀 to-do

- [x] 마이페이지 탭바 연결
- [ ] 프로필 정보 뷰 구현
- [ ] 테이블뷰 섹션 구현
