### ISSUE TITLE
[FEAT] 구매 폼 상세보기 UI 구현

### ISSUE THREAD

**Issue by zzikbu** [CatDesignProject/CUKZ-FE#15]
# 👀 이슈 (issue)

구매 폼 상세보기 UI 구현

# 🚀 to-do

- [x] 상품 이미지 컬렉션뷰 구현
- [x] 찜, 구매하기 하단 고정 플로팅 View 구현
- [x] 작성자 정보, 상품 설명 구현
