### ISSUE TITLE
[FEAT] 상품 상세보기 UI 수정 및 API 연결

### ISSUE THREAD

**Issue by zzikbu** [CatDesignProject/CUKZ-FE#56]
# 👀 이슈 (issue)
상품 상세보기 UI 변경 및 API 연결

# 🚀 to-do

- [x] 총대 리뷰 보기 버튼 추가
- [x] 상품 상세보기 내 총대 리뷰보기 API 연결
- [x] 상품 상세보기 API 연결
- [x] 새로고침
