### ISSUE TITLE
[Refactor] API 수정에 따른 코드 수정

### ISSUE THREAD

**Issue by zzikbu** [CatDesignProject/CUKZ-FE#60]
# 👀 이슈 (issue)
API 수정에 따른 코드 수정

# 🚀 to-do

- [x] 로그인 관련 코드 수정
- [x] 상품 관련 코드 수정
- [x] 좋아요 관련 코드 수정
- [x] 리뷰 관련 코드 수정
